services:
    sogos_dynamo_db.connector:
        class: Sogos\Bundle\DynamoDBBundle\Connector
        arguments: ["@logger", %dynamodb_database_name%, "%sogos_dynamo_db.connector.region%", "%sogos_dynamo_db.connector.dynamodb_read_capacity_units%", "%sogos_dynamo_db.connector.dynamodb_write_capacity_units%"]
