services:
    sogos_dynamo_db.connector:
        class: Sogos\Bundle\DynamoDBBundle\Connector
        arguments: ["@logger", %dynamodb_database_name%, %dynamodb_region%, %dynamodb_read_capacity_units%, %dynamodb_write_capacity_units%]
